name: "Loading Test"
description: "Loading test - 1 million entities"
schema: "loading_schema.gql"

dataGenerator: "emptyLoadingTest"
queries: "loading_data_queries.yml"
repeatsPerQuery: 1
deleteInsertedConcepts: false
traceDeleteInsertedConcepts: false

concurrency:
  clients: 1
  uniqueKeyspaces: false