graphName: "social_network"
schema: "social_network.gql"
queries: "queries.yml"
scales:
  - 5000
#  - 5000
#  - 10000
repeatsPerQuery: 5
  # TODO
  # concurrency:
  #   clients: 1
# mixed:
# replication: 1